### ISSUE TITLE
Delete the master branch that is obsolete on github

### ISSUE THREAD

**Issue by felipedavi** [caiovale1921/Jogo_da_Velha#3]
> According to the pull request #2 . You can delete the master branch that is no longer needed by following the steps below:

## Removing the local branch

`git branch -D master`

## removing the remote branch

`git push origin --delete`

## Or Following in the Footsteps of the Github Wiki

[Link](https://docs.github.com/pt/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository)

### To prevent recreating repositories with the deprecated branch run the following command
`git config --global init.defaultBranch "main"`

**Comment by caiovale1921** [comment]
Thank you very much for your contribution **@felipedavi**, the old branch has already been removed.
